# Generated by Django 2.1.4 on 2018-12-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='cheked',
            new_name='checked',
        ),
    ]
